### ISSUE TITLE
SIGBUS when using addTaskHighBackground()

### ISSUE THREAD

**Issue by vojta** [wcgallego/pecl-gearman#6]
I'm using something like

```
$gc = new \GearmanClient();
$gc->addServer();
$gc->addTaskLowBackground('myjob', 'xyz', null, sha1('xyz'));
$gc->runTasks();
```

It works, the worker gets the request without any problem. But then it crashes the php-fpm process. When I try it in CLI, I get SIGBUS. This is the output I got using gdb:

```
Program received signal SIGBUS, Bus error.
zend_mm_alloc_small (heap=0x7ffff4000040, ptr=<value optimized out>, size=<value optimized out>, copy_size=256) at /usr/src/debug/php-7.0.3/Zend/zend_alloc.c:1291
1291            heap->free_slot[bin_num] = p->next_free_slot;
```

Currently, I can't reproduce the problem without using our whole codebase. That means, when I call these GearmanClient methods in a small simple script, it works without a problem. All I know is that it works on PHP 5.5.32 and not on PHP7.

**Comment by vojta** [comment]
I tried the current version, compiled today, but I got a segfault:

```
kernel: php70[25378]: segfault at 0 ip 00007fd4e55f5714 sp 00007ffc314989d0 error 6 in gearman.so[7fd4e55e9000+15000]
```

**Comment by wcgallego** [comment]
Sorry @vojta, still trying to reproduce this and failing. I know there's been a lot of back and forth (thanks again!) between tickets, so not sure if it's cleaned up since. Apologies if you're still waiting on this.

if it's failing on zend_mm_alloc_small, that means it was probably trying to allocate something excessively large. I've pushed a small change that handles memory leaks when destroy Gearman Client objects, but all my tests I've written and the ones you've posted for various issues still succeed, so I'm not sure where the problem lies. Argh.

Do you have a core dump you could send? That might help point out what's wrong.

**Comment by wcgallego** [comment]
following up @vojta, were you ever able to get a core dump to share?

**Comment by wcgallego** [comment]
@vojta I think several fixes might have helped resolve this. Latest branch should be up to date with several important merges. Give it a shot and lemme know!

**Comment by vojta** [comment]
@wcgallego I'm testing the latest branch and it seems much better. Occasionally, we are still getting some segfaults, I'm trying to collect a core dump.

**Comment by vojta** [comment]
The segfault occurs when i call pcntl_fork() without unsetting the GearmanWorker object. I should not do that, I'll fix my code. I'm just saying "this used to work on PHP5". But it's not a showstopper for me. The original segfault is resolved. Closing, thank you!
